# Generated by Django 4.2.4 on 2023-08-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Direccion', models.TextField()),
                ('Lat', models.FloatField()),
                ('Long', models.FloatField()),
            ],
        ),
    ]
