# Generated by Django 4.2.5 on 2023-11-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0004_calidad_aire_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicaciones',
            name='calidad_aire',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='calidad_aire',
        ),
    ]
